Bulls_And_Cows/Bulls_And_Cows.Web/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bulls_And_Cows.Data.Entities;
using Bulls_And_Cows.Services.Contracts;
using Bulls_And_Cows.Web.Models;
using Bulls_And_Cows.Web.ViewModelsMappers;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Bulls_And_Cows.Web.Controllers
{
    public class GameController : Controller
    {
        private readonly IGameService gameService;
        private readonly UserManager<User> userManager;

        public GameController(IGameService gameService, UserManager<User> userManager)
        {
            this.gameService = gameService;
            this.userManager = userManager;
        }

        //[HttpGet]
        //public IActionResult Create()
        //{
        //    //var gameViewModel = new GameViewModel();
        //    return View();
        //}

        //[HttpPost]
        public async Task<IActionResult> Create()
        {
            var userId = (await userManager.GetUserAsync(User)).Id;

            //var gameDto = gameViewModel.GetDto();

            var gameDto = await this.gameService.CreateGameAsync(userId);
            var gameVM = gameDto.GetViewModel();

            return View("Views/Game/Play.cshtml", gameVM);
        }

       
        [HttpPut]
        public async Task<IActionResult> Play(GameViewModel gameViewModel)
        {
            var gameDto = await this.gameService.PlayAsync(gameViewModel.GetDto());
            var gameVM = gameDto.GetViewModel();

            return View(gameVM);
        }
    }
}

Bulls_And_Cows/Bulls_And_Cows.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bulls And Cows</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bulls And Cows</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="GetTop25Users">Top Players</a>
                        </li>
                        @if (User.IsInRole("Member"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Create">New Game</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="GetAllUsers">Users</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Bulls And Cows - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>